### ISSUE TITLE
Set origin to git upstream

### ISSUE THREAD

**Issue by jdfreder** [jovyan/jupyter-devinstall#30]
@fperez Min, and Matthias all said they use upstream as origin.  This is the opposite of what this tool does.  I know Brian and I both set origin to our forked copy of the repo, which is what this tool does.  @SylvainCorlay what do you do normally?  

We definitely need a flag to support both use cases.  The only question is, which becomes the default?

**Comment by SylvainCorlay** [comment]
`origin` is my fork. (I think that @jasongrout does the same)

**Comment by jdfreder** [comment]
I'll add a flag for the others then, we can continue to discuss it if people express interest :)

**Comment by jasongrout** [comment]
+1 to origin being my fork.  That's where I usually push.

**Comment by jasongrout** [comment]
(I guess we see who is used to pushing to master from ye olde days, and who is used to submitting PRs :).

**Comment by fperez** [comment]
No, it's for pulling convenience, so that `origin/master` is always upstream, to start new branches off.  And now I've switched to @minrk's approach of having origin checked out over https, which makes accidental pushes impossible (no ssh keys active in the background).

I really like that setup:

```
(master)denali[notebook]> git remote -v
fperez  git@github.com:fperez/notebook.git (fetch)
fperez  git@github.com:fperez/notebook.git (push)
origin  https://github.com/jupyter/notebook.git (fetch)
origin  https://github.com/jupyter/notebook.git (push)
```

But, whatever works for folks: I think this is one of those habits where the tool should adapt to the user, not impose on the user.  We've all found a pattern that works for us, it's easy enough to have a tool that works with each of those patterns.
